

BEGIN TRANSACTION PRUEBA1 
INSERT INTO CLIENTE_BANCA VALUES('001', 'Manuel Rios Maldonado', 9000); 
INSERT INTO CLIENTE_BANCA VALUES('002', 'Pablo Perez Ortiz', 5000); 
INSERT INTO CLIENTE_BANCA VALUES('003', 'Luis Flores Alvarado', 8000); 
COMMIT TRANSACTION PRUEBA1

SELECT * FROM CLIENTE_BANCA 

 BEGIN TRANSACTION PRUEBA2 
INSERT INTO CLIENTE_BANCA VALUES('004','Ricardo Rios Maldonado',19000; 
INSERT INTO CLIENTE_BANCA VALUES('005','Pablo Ortiz Arana',15000); 
INSERT INTO CLIENTE_BANCA VALUES('006','Luis Manuel Alvarado',18000); 

SELECT * FROM CLIENTE_BANCA
SELECT * FROM CLIENTE_BANCA 

SELECT * FROM CLIENTE_BANCA where NoCuenta='001' 

ROLLBACK TRANSACTION PRUEBA2 
SELECT * FROM CLIENTE_BANCA 

BEGIN TRANSACTION PRUEBA3 
INSERT INTO TIPOS_MOVIMIENTOS VALUES('A','Retiro Cajero Automatico'); 
INSERT INTO TIPOS_MOVIMIENTOS VALUES('B','Deposito Ventanilla'); 
COMMIT TRANSACTION PRUEBA3 

BEGIN TRANSACTION PRUEBA4 
INSERT INTO MOVIMIENTOS VALUES('001','A',GETDATE(),500); 
UPDATE CLIENTE_BANCA SET SALDO = SALDO -500 
WHERE NoCuenta='001' 
COMMIT TRANSACTION PRUEBA4 

SELECT * FROM Cliente_Banca
SELECT * FROM Movimientos

BEGIN TRANSACTION PRUEBA5 
INSERT INTO CLIENTE_BANCA VALUES('005','Rosa Ruiz Maldonado',9000); 
INSERT INTO CLIENTE_BANCA VALUES('006','Luis Camino Ortiz',5000); 
INSERT INTO CLIENTE_BANCA VALUES('001','Oscar Perez Alvarado',8000); 


IF @@ERROR = 0 
COMMIT TRANSACTION PRUEBA5 
ELSE 
BEGIN 
PRINT 'A transaction needs to be rolled back' 
ROLLBACK TRANSACTION PRUEBA5 
END 

SELECT * FROM Movimientos